# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I-cVeoOpSvBkeDonbQWDMNVz_18XXVbJ
"""

import os
HOME = os.getcwd()
print(HOME)



!pip install ultralytics

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
!yolo task=detect mode=predict model=yolo12s.pt conf=0.25 source='https://media.roboflow.com/notebooks/examples/dog.jpeg' save=True

# Commented out IPython magic to ensure Python compatibility.
!mkdir {HOME}/datasets
# %cd {HOME}/datasets

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="wNDHQYqO7YSFOUwl0QV0")
project = rf.workspace("parth-p45h7").project("license_plate-igwuf")
version = project.version(2)
dataset = version.download("yolov8")

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}   # go to home directory

!yolo task=detect mode=train model=yolov8n.pt \
     data={dataset.location}/data.yaml \
     epochs=100 imgsz=640 plots=True

